---
kind: pipeline
name: default

steps:
  - name: build
    image: ghcr.io/getzola/zola:v0.17.2
    entrypoint: ["/bin/zola"]
    command: ["build"]

  - name: deploy
    image: drillster/drone-rsync
    settings:
      hosts: ["it-new.pedf.cuni.cz"]
      user: drone
      source: public/*
      target: /home/www/web-kittv/
      recursive: true
      delete: true
    environment:
      RSYNC_KEY:
        from_secret: ssh_private_key
