base_url = "https://it.pedf.cuni.cz"
title = "KITTV"

compile_sass = true
highlight_code = false
build_search_index = false

[extra]

nav_primary = [
	{path = "", name = "Katedra"},
	{path = "", name = "Uchazeči"},
	{path = "", name = "Studenti"},
	{path = "", name = "Vědecká činnost"}
]

nav_secondary = [
	{path = "https://cuni.cz", name = "Univerzita Karlova"},
	{path = "https://pedf.cuni.cz", name = "Pedagogická fakulta"}
]

nav_rambotron = [
	{path = "", name = "Harmonogram roku"},
	{path = "", name = "Termíny přijímacího řízení"},
	{path = "", name = "Témata závěrečných prací"},
	{path = "", name = "Okruhy k SZZ"}
]
