base_url = "https://it.pedf.cuni.cz"
title = "KITTV"

compile_sass = true
highlight_code = false
build_search_index = false


[markdown]

smart_punctuation = true
external_links_no_referrer = true


[extra]

nav_primary = [
	{path = "katedra", name = "Katedra"},
	{path = "uchazeci", name = "Uchazeči"},
	{path = "studenti", name = "Studenti"},
	{path = "vedecka-cinnost", name = "Vědecká činnost"}
]

nav_secondary = [
	{path = "https://cuni.cz", name = "Univerzita Karlova"},
	{path = "https://pedf.cuni.cz", name = "Pedagogická fakulta"}
]

nav_rambotron = [
	{path = "", name = "Harmonogram roku"},
	{path = "", name = "Termíny přijímacího řízení"},
	{path = "", name = "Témata závěrečných prací"},
	{path = "", name = "Okruhy k SZZ"}
]

nav_footer = [
	{path = "", name = "Bakalářská studia"},
	{path = "", name = "Magisterská studia"},
	{path = "", name = "Harmonogram ak. roku"},
	{path = "", name = "Formuláře"},
]
