base_url = "https://it.pedf.cuni.cz/"
title = "Katedra informačních technologií a technické výchovy"

default_language = "cs"
compile_sass = true
minify_html = true

generate_feeds = false
feed_filenames = ["atom.xml"]

build_search_index = false
generate_sitemap = true
generate_robots_txt = true


[markdown]
highlight_code = false
smart_punctuation = true

external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true


[extra]

nav_primary = [
	{path = "katedra", name = "Katedra"},
	{path = "uchazeci", name = "Uchazeči"},
	{path = "studenti", name = "Studenti"},
	{path = "vedecka-cinnost", name = "Věda"}
]

nav_secondary = [
	{path = "https://cuni.cz", name = "Univerzita Karlova"},
	{path = "https://pedf.cuni.cz", name = "Pedagogická fakulta"}
]

nav_rambotron = [
	{path = "https://pedf.cuni.cz/PEDF-606.html", name = "Harmonogram roku"},
	{path = "/uchazeci/prijimaci_rizeni/", name = "Termíny přijímacího řízení"},
	{path = "/studenti/zav_prace/", name = "Témata závěrečných prací"},
	{path = "/studenti/szz/", name = "Okruhy k SZZ"},
	{path = "/uchazeci/zajmove-programy-czv/", name = "Kurzy pro učitele"}
]

nav_footer = [
	{path = "/katedra/sidlo-pracoviste/", name = "Sídlo pracoviště"},
	{path = "/katedra/pracovnici/", name = "Pracovníci"},
	{path = "/studenti/ssp/", name = "Studenti se spec. potřebami"},
	{path = "https://cunicz.sharepoint.com/sites/PedF-Int", name = "Intranet"},
	{path = "/pristupnost/", name = "Prohlášení o přístupnosti"},
]
