name: Build and Deploy Zola Site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build site with Zola
        uses: docker://ghcr.io/getzola/zola:v0.17.2
        with:
          args: build

      - name: Upload public directory
        uses: actions/upload-artifact@v4
        with:
          name: public-site
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Download site artifact
        uses: actions/download-artifact@v4
        with:
          name: public-site
          path: public

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via rsync
        run: |
          rsync -az --delete -e "ssh -o StrictHostKeyChecking=no" public/* drone@it-new.pedf.cuni.cz:/home/www/web-kittv/
